### ISSUE TITLE
adding saved links

### ISSUE THREAD

**Issue by antonioortegajr** [wp-api-libraries/wp-idxbroker-api#7]
Using the lib I am only returning false when trying to add a saved link. 400 is the status code I get from the API call.

Was trying to pass
`'linkName' => 'Good_side_of_tracks',
 'pageTitle' => 'Good_side_of_tracks',
 'linkTitle' => 'Good_side_of_tracks',
 'queryString' => array('idxID' => 'a001', 'hp' => '200000')`
in my array.

Is PUT and POST supported for savedlinks or leads?

**Comment by sfgarza** [comment]
Hi @antonioortegajr!

The library defaults  all calls to `GET` if the method field isn't explicitly set in the request, but it does support `POST` & `PUT`.

This should work for creating a new savedlink through the API:
```
$idx_api = new IdxBrokerAPI('xxxxxxxxxxxxxxx');

$fields['method'] = 'PUT';
$fields['body'] = array(
 	'linkName' => 'Good_side_of_tracks',
 	'pageTitle' => 'Good_side_of_tracks',
 	'linkTitle' => 'Good_side_of_tracks',
 	'queryString' => array('idxID' => 'a001', 'hp' => '200000')
);

$results = $idx_api->build_request( 'clients/savedlinks', $fields )->request();
```

On a side note. I'm planning on expanding the library to add route specific methods to make usage a lot easier. So later on, making a new savedlink will look like:
```
$results = $idx_api->clients_savedlinks( 
                     'Good_side_of_tracks', 
                     'Good_side_of_tracks', 
                     'Good_side_of_tracks', 
                      array('idxID' => 'a001', 'hp' => '200000')
);
```
and updating will be (where 12345 is savedLinksID):
```
$results = $idx_api->clients_savedlinks( 
                     'Good_side_of_tracks', 
                     'Good_side_of_tracks', 
                     'Good_side_of_tracks', 
                     array('idxID' => 'a001', 'hp' => '200000'),
                     12345
);
```
